# Generated by Django 4.1.1 on 2022-09-29 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('M', 'mobile'), ('L', 'laptop'), ('TW', 'top wear'), ('BW', 'bottom wear')], max_length=2),
        ),
    ]
